### ISSUE TITLE
Inconsistency in Solid properties between tasks 2 and 5

### ISSUE THREAD

**Issue by MakisH** [precice/community-training#15]
I noticed we have some differences in the `solidModel.inp` between tasks 2 (previously `dynamicModel.inp`) and 5. These different parameters are not currently motivated. @Ccaccia73 was there a particular reason to change these values, or can we use the same in both? I guess it makes more sense to update Task 2 to use the values from Task 5.

- Task 2 skeleton: https://github.com/precice/community-training/blob/main/fsi-workflow/02_solidSimulation/skeleton/solidModel.inp
- Task 2 solution: https://github.com/precice/community-training/blob/main/fsi-workflow/02_solidSimulation/solution/solidModel.inp
- Task 5 skeleton: https://github.com/precice/community-training/blob/main/fsi-workflow/05_FSI/skeleton/Solid/solidModel.inp
- Task 5 solution: https://github.com/precice/community-training/blob/main/fsi-workflow/05_FSI/solution/FSI_water/Solid/solidModel.inp

**Comment by Ccaccia73** [comment]
Yes they are different because I was trying to have some deformation in task 2 and have reasonable material properties in task 5. It would be easier to update task 2.

**Comment by MakisH** [comment]
I can do that.

**Comment by MakisH** [comment]
If you don't have time, I can also just motivate the change for now.

**Comment by Ccaccia73** [comment]
I am working on it

**Comment by Ccaccia73** [comment]
I have updated task.md, skeleton and solution to be consistent with task 5. I have also added a screen capture of the updated solution in images (wing_deformed.png) please look at it, I have seen that you updated the previous one.

**Comment by MakisH** [comment]
Thank you for the quick fix!

Related commit: https://github.com/precice/community-training/commit/c6b5f2b943728b6e475301a9cfcad776d9e24021

I assume that the material is now close to "Polystyrene or ABS". I will update that in task 5.

I still see some differences, which I can just document:

- time step and end time, damping
- ramp load

![Screenshot from 2024-09-18 16-56-33](https://github.com/user-attachments/assets/39783aa5-6448-4219-80f3-cff3ff3ccc6c)

**Comment by MakisH** [comment]
Documented in https://github.com/precice/community-training/commit/7f47948703460276d990ca30cf97ec1a4cfc268d
